[package]
name = "ruspiro-lock"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.3.0" # remember to update html_root_url
description = """
Simple atomic locking and safe data access (mutual exclusive) cross cores on Raspberry Pi.
"""
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-lock/tree/v0.3.0"
documentation = "https://docs.rs/ruspiro-lock/0.3.0"
readme = "README.md"
keywords = ["RusPiRo", "spinlock", "semaphore", "datalock", "raspberrypi"]
categories = ["no-std", "embedded"]
edition = "2018"

[badges]
travis-ci = { repository = "RusPiRo/ruspiro-lock", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]

[dependencies]
ruspiro-interrupt-core = { path = "../interrupt/core", version = "0.3" }

[features]
default = ["ruspiro_pi3"]
ruspiro_pi3 = []
