#***********************************************************************************************************************
# cargo make tasks to build the example for the Raspberry Pi
#***********************************************************************************************************************

# AARCH64 specific profile environment varialbles
[env.development]
CC = "aarch64-none-elf-gcc"
AR = "aarch64-none-elf-ar"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53"

# AARCH64 specific pipeline CI env. variables. "aarch64-none-elf" is not available there as it seems
[env.pipeline]
CC = "aarch64-linux-gnu-gcc"
AR = "aarch64-linux-gnu-ar"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53"

[tasks.build]
env = { FEATURES = "async_locks" }
command = "cargo"
args = ["build", "--release", "--features", "${FEATURES}"]

[tasks.clippy]
env = { FEATURES = "async_locks" }
command = "cargo"
args = ["clippy", "--features", "${FEATURES}"]

[tasks.doc]
env = { FEATURES = "async_locks" }
command = "cargo"
args = ["doc", "--target", "aarch64-unknown-linux-gnu", "--open", "--features", "${FEATURES}"]

[tasks.doctest]
env = { FEATURES = "async_locks" }
command = "cargo"
args = ["test", "--doc", "--features", "${FEATURES}"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.publish_dry]
env = { FEATURES = "async_locks" }
command = "cargo"
args = ["publish", "--dry-run", "--features", "${FEATURES}"]

[tasks.publish]
env = { FEATURES = "async_locks" }
command = "cargo"
args = ["publish", "--token", "${CRATES_TOKEN}", "--allow-dirty", "--features", "${FEATURES}"]